### ISSUE TITLE
What means 'Train_dir.txt' and 'Val_dir.txt'?

### ISSUE THREAD

**Issue by SiYeon-Kwon** [mobarakol/3D_Attention_UNet#1]
I can't find any directory in this folder named 'Train_dir.txt' and 'Val_dir.txt'.

Can you tell me what means that?

**Comment by mobarakol** [comment]
They are inside foldXX folder: https://github.com/mobarakol/3D_Attention_UNet/tree/c8d13f8f455365dc0af7975208ae44b1cca84ac4/survival_prediction/python/Classification/Fold4

**Comment by SiYeon-Kwon** [comment]
Oh, thanks a lot!!

Even though I entered the folder as a path, the following error occurs, can you help me?

IndexError: string index out of range

The problem occurs on line 123 of base_nn.py, test_dataset=HEMDataset_test(text_dir=test_file) and line 84, self.req_tar.append(4).
